// <auto-generated />
using System;
using Arcane.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Arcane.Core.Migrations
{
    [DbContext(typeof(ArcaneDbContext))]
    partial class ArcaneDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Arcane.Core.Models.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("DataEncrypted")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("DataNonce")
                        .HasColumnType("BLOB");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ExternalPathEncrypted")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ExternalPathNonce")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("FileNameEncrypted")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("FileNameNonce")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStoredExternally")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("Arcane.Core.Models.Entities.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ContentEncrypted")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ContentNonce")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Mood")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TitleEncrypted")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("TitleNonce")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("Arcane.Core.Models.Entities.EntryTag", b =>
                {
                    b.Property<Guid>("EntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("EntryId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("EntryTags");
                });

            modelBuilder.Entity("Arcane.Core.Models.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Arcane.Core.Models.Entities.VaultProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Argon2Iterations")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Argon2MemoryKiB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Argon2Parallelism")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoLockMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EditorFontSize")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUnlockedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ThemePreference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("VerificationCiphertext")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("VerificationNonce")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("VaultProfiles");
                });

            modelBuilder.Entity("Arcane.Core.Models.Entities.Attachment", b =>
                {
                    b.HasOne("Arcane.Core.Models.Entities.Entry", "Entry")
                        .WithMany("Attachments")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("Arcane.Core.Models.Entities.EntryTag", b =>
                {
                    b.HasOne("Arcane.Core.Models.Entities.Entry", "Entry")
                        .WithMany("EntryTags")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arcane.Core.Models.Entities.Tag", "Tag")
                        .WithMany("EntryTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Arcane.Core.Models.Entities.Entry", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("EntryTags");
                });

            modelBuilder.Entity("Arcane.Core.Models.Entities.Tag", b =>
                {
                    b.Navigation("EntryTags");
                });
#pragma warning restore 612, 618
        }
    }
}
